import javax.swing.JOptionPane;

/**mmn11:q1-bulls and cows
 * 
 * Explanation:the aim of this game is to guess a random number generated by the computer.
 * at each turn the user input 4 digit and the program return how many exactly hits he guess-bulls
 * and how many correct number but in the wrong place-hence cows.
 * The game ends when the user guess the whole 4 digit in the correct order.
 * In this class the we execute the logic implement in the other class,and handle the pop-ups.
 * @coded by Yahav Nir-Advanced Programming with Java 
 */

public class Main {
	public static void main(String[] args) {
		boolean game_running = true;
		String message_received = "";
		LogicOfGame game = new LogicOfGame();
		String guesses_made = "";

		while(game_running == true) {
			//each time asks for the input
			String guess = JOptionPane.showInputDialog("Please enter your guess: "+"\n guess should inculde 4 unrepeated digit");	

			//add the new message with the last guesses			
			JOptionPane.showMessageDialog(null, (message_received = game.check_guess(guess)) +"\nPrevious guesses: "+ guesses_made);
			//save previous guesses only if they were valid
			if(message_received.startsWith("Your"))										
				guesses_made = guesses_made +"\n"+ message_received;

			//end of the game,present the possibility to start over or exit
			if(message_received.startsWith("Good") == true) {
				guess = JOptionPane.showInputDialog("Play again? enter Y");
				if(guess.contains("Y")) {
					//if the user want to start over-create another instant of the object LogicOfGame
					game = new LogicOfGame();												
					guesses_made = "";
				}
				else {
					JOptionPane.showMessageDialog(null, "Thanks for playing :)");
					//when changed to false-the game ends
					game_running = false;														
				}
			}
		}
	}
}
